apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
    {{- include "fullstack-app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: frontend
    release: {{ .Release.Name }}
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
